---
title: "Cervantes map"
author: "Miguel Betti"
date: "22/10/2024"
output: html_document
---

#J'installe les librairies et les packages nécessaires: knitr, leaflet, etc.

```{r, setup, fig.show=hold, fig.margin=TRUE}
if(!require("knitr")){
  install.packages("knitr")
  library(knitr)
}
knitr::opts_chunk$set(echo = TRUE, fig.width=20)
```

```{r, warning=FALSE, results='hide'}
if(!require("leaflet")){
  install.packages("leaflet")
  library(leaflet)
}
if(!require("sp")){
  install.packages("sp")
  library(sp)
}
if(!require("RColorBrewer")){
  install.packages("RColorBrewer")
  library(RColorBrewer)
}
if(!require("htmlwidgets")){
  install.packages("htmlwidgets")
  library(htmlwidgets)
}
if(!require("htmltools")){
  install.packages("htmltools")
  library(htmltools)
}
if(!require("leaflet.extras")){
  install.packages("leaflet.extras")
  library(leaflet.extras)
}
if(!require("geojsonio")){
  install.packages("geojsonio")
  library(geojsonio)
}
if(!require("rjson")){
  install.packages("rjson")
  library(rjson)
}
if(!require("leaftime")){
  install.packages("leaftime")
  library(leaftime)
}

```

#Je charge les données de travail: les noms de lieux issus des pièces de Lope de Vega, divisés par pièces et par genre ("comedia" et "drama")
```{r}
setwd("C:/Users/betti/Desktop/Cervantes_map/Cervantes_map")
```

```{r, results='hide'}
Parte_I  <- read.csv("data/Places/Parte_I.csv")
Parte_I$lng <- as.numeric(Parte_I$lng)
Parte_I$lat <- as.numeric(Parte_I$lat)
```

```{r, results='hide'}
Parte_II  <- read.csv("data/Places/Parte_II.csv")
Parte_II$lng <- as.numeric(Parte_II$lng)
Parte_II$lat <- as.numeric(Parte_II$lat)
```

#Je prépare la carte
```{r}
#Je prépare la carte
map <- leaflet() %>%
  addProviderTiles(providers$Esri.NatGeoWorldMap) %>% 
  setView(lng = -40, lat = 40, zoom = 2.4) %>%
  
  #J'ajoute les points issus des pièces
  addCircleMarkers(lng = Parte_I$lng, 
                   lat = Parte_I$lat,
                   group = "Primera parte",
                   color = "blue",
                   weight = 1,
                   radius = ~sqrt(Parte_I$menciones) * 4,
                   fillOpacity = 0.5,
                   label = ~paste(Parte_I$lugar, Parte_I$menciones)) %>%
  
  addCircleMarkers(lng = Parte_II$lng, 
                   lat = Parte_II$lat,
                   group = "Segunda parte",
                   color = "red",
                   weight = 1,
                   radius = ~sqrt(Parte_II$menciones) * 4,
                   fillOpacity = 0.5,
                   label = ~paste(Parte_II$lugar, Parte_II$menciones)) %>%
  
  #J'ajoute une fonction reset
  addResetMapButton() %>%
  
  #J'ajoute un panneau de contrôle
  addLayersControl(baseGroups = c("El Quijote"),
                   overlayGroups = c("Primera parte", "Segunda parte"),
                   options = layersControlOptions(collapsed = TRUE)) %>%
  
  addLegend("bottomleft", 
            colors = c("transparent"),
            labels = c("Mapa y extracción de datos: Miguel Betti - miguel.betti@unige.ch"),
            title = "El mapa del Quijote:")

# Affiche la carte
map
```
```{r}
map <- leaflet() %>%
  addProviderTiles(providers$Esri.NatGeoWorldMap) %>% 
  setView(lng = 7.188, lat = 21.094, zoom = 5) %>%  # Ajustez le point central et le niveau de zoom selon vos données
  
  addCircleMarkers(lng = Parte_I$lng, 
                   lat = Parte_I$lat,
                   group = "Primera parte",
                   color = "blue",
                   weight = 1,
                   radius = ~sqrt(Parte_I$menciones) * 4,
                   fillOpacity = 0.5,
                   label = ~paste(Parte_I$lugar, Parte_I$menciones))

# Affichez la carte
map



```